name: Build Swift Dylib
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile Swift to Dylib
        run: |
          swiftc -emit-library -target arm64-apple-ios14.0 -sdk $(xcrun --sdk iphoneos --show-sdk-path) main.swift -o Plugin.dylib
      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v3
        with:
          name: KeyPlugin
          path: Plugin.dylib
