name: Build Dylib
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile Dylib for iOS
        run: |
          clang -dynamiclib -arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -miphoneos-version-min=14.0 main.m -o Plugin.dylib -framework UIKit -framework Foundation
      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v3
        with:
          name: KeyPlugin
          path: Plugin.dylib
